### ISSUE TITLE
Cannot run olapy init

### ISSUE THREAD

**Issue by WiirinAnn** [abilian/olapy#16]
It appears 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\olapy-script.py", line 11, in <module>
    load_entry_point('olapy==0.7.5', 'console_scripts', 'olapy')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\programdata\anaconda3\lib\site-packages\olapy-0.7.5-py3.7.egg\olapy\__main__.py", line 7, in <module>
    from .core.services.xmla import runserver
  File "c:\programdata\anaconda3\lib\site-packages\olapy-0.7.5-py3.7.egg\olapy\core\services\xmla.py", line 27, in <module>
    from .xmla_lib import XmlaProviderLib
  File "c:\programdata\anaconda3\lib\site-packages\olapy-0.7.5-py3.7.egg\olapy\core\services\xmla_lib.py", line 6, in <module>
    import pandas as pd
  File "c:\programdata\anaconda3\lib\site-packages\pandas\__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "c:\programdata\anaconda3\lib\site-packages\pandas\compat\__init__.py", line 430, in <module>
    import typing
  File "c:\programdata\anaconda3\lib\site-packages\typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "c:\programdata\anaconda3\lib\site-packages\typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

Note: I'm using python 3.7.1 << Is this python version compatible?

**Comment by mouadhkaabachi** [comment]
Hi WiirinAnn,
did you install olapy from pypi or github?
If it's from pypi, can you try to install it from github repo ?
1) git clone git://github.com/abilian/olapy.git
2) cd olapy
3) python setup.py install
4) olapy init
and tell me if you have the same problem or not
(I think the problem is related to olapy dependencies that are not up to date in pypi version, (we will make a new release for that))

**Comment by WiirinAnn** [comment]
Thanks for your promp reply.

I have installed it using git clone and it appeared that error message.
By the way, I’ve uninstalled python3 from my computer and have tried out
with this package with python 2.7.15, it’s working fine now.

Cheers,
